image: python:3.13-slim

stages:
  - build
  - qa
  - docs
  - test

build:js:
  image: node:24-alpine
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - ausgsteckt/ausgsteckt/static/node_modules/
    expire_in: 1 day

.install:
  stage: build
  before_script:
    - pip install uv
  script:
    - uv sync --group dev --group test --group docs
  artifacts:
    expire_in: 1 day
    paths:
      - .venv

install:python3.13:
  extends: .install

ruff:check:
  stage: qa
  script:
    - source .venv/bin/activate
    - ruff --version
    - ruff check .
  allow_failure: true
  dependencies:
    - install:python3.13

ruff:format:
  stage: qa
  script:
    - source .venv/bin/activate
    - ruff format --check .
  allow_failure: true
  dependencies:
    - install:python3.13

ty:
  stage: qa
  script:
    - source .venv/bin/activate
    - ty --version
    - ty check
  allow_failure: true
  dependencies:
    - install:python3.13

.pages:
  stage: docs
  script:
    - apt update
    - apt install make
    - . .venv/bin/activate
    - cd docs
    - make html
  dependencies:
    - install:python3.13

build:pages:
  extends: .pages
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 7 day
  except:
    - master

pages:
  extends: .pages
  after_script:
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master

.test:
  stage: test
  services:
    - postgis/postgis:18-3.6-alpine
  variables:
    DJANGO_DATABASE_URL: postgis://django:secret@postgis:5432/django_test
    DJANGO_LOG_FILE: /dev/null
    POSTGRES_DB: django_test
    POSTGRES_USER: django
    POSTGRES_PASSWORD: secret

  before_script:
    - apt-get update
    - apt-get install -y python3-gdal
    - source .venv/bin/activate
    - cd ausgsteckt
  script:
    - python manage.py test
  coverage: '/^TOTAL.*\s([0-9\.]+)%$/'
  artifacts:
    reports:
      junit: report.xml
