image: python:3.10

stages:
  - build
  - install
  - qa
  - docs
  - test

flake8:
  stage: qa
  script:
    - pip install ruff
    - ruff .
  allow_failure: true

build:js:
  image: node:12-alpine
  stage: build
  script:
    - yarn install --modules-folder ausgsteckt/ausgsteckt/static/node_modules/
  artifacts:
    paths:
      - ausgsteckt/ausgsteckt/static/node_modules/
    expire_in: 1 day

.install:
  stage: install
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -U wheel pip setuptools poetry
  script:
    - poetry install --with dev,test,docs
  artifacts:
    expire_in: 1 day
    paths:
      - .venv

install:python3.10:
  extends: .install
  image: python:3.10

install:python3.11:
  extends: .install
  image: python:3.11

.pages:
  stage: docs
  script:
    - apt install make
    - . .venv/bin/activate
    - cd docs
    - make html
  image: python:3.10
  dependencies:
    - install:python3.10

build:pages:
  extends: .pages
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 7 day
  except:
    - master

pages:
  extends: .pages
  after_script:
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master

.test:
  stage: test
  services:
    - mdillon/postgis:12-alpine
  variables:
    DATABASE_URL: postgis://django:secret@mdillon-postgis:5432/django_test
    DJANGO_LOG_FILE: /dev/null
    POSTGRES_DB: django_test
    POSTGRES_USER: django
    POSTGRES_PASSWORD: secret

  before_script:
    - apt-get update
    - apt-get install -y python3-gdal
    - source .venv/bin/activate
    - cd ausgsteckt
  script:
    - python manage.py test
  coverage: '/^TOTAL.*\s([0-9\.]+)%$/'
  artifacts:
    reports:
      junit: report.xml

test:python3.10:
  extends: .test
  image: python:3.10
  dependencies:
    - install:python3.10

test:python3.11:
  extends: .test
  image: python:3.11
  dependencies:
    - install:python3.11
