version: '3.7'

services:
  db:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ausgsteckt
  django:
    build: .
    environment:
      DATABASE_URL: postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/ausgsteckt
    depends_on:
      - db
    volumes:
      - public:/srv

  nginx:
    build: docker/nginx/
    ports:
      - "8001:80"
    depends_on:
      - django
    volumes:
      - public:/srv

volumes:
  public:
