services:
  db:
    image: postgis/postgis:18-3.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ausgsteckt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ausgsteckt}
      POSTGRES_DB: ausgsteckt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ausgsteckt} -d ausgsteckt"]
      interval: 5s
      timeout: 5s
      retries: 10
  django:
    build: .
    environment:
      DJANGO_DATABASE_URL: postgis://${POSTGRES_USER:-ausgsteckt}:${POSTGRES_PASSWORD:-ausgsteckt}@db:5432/ausgsteckt
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./public/static:/srv/static
      - ./public/media:/srv/media

  nginx:
    build: docker/nginx/
    ports:
      - "8001:80"
    depends_on:
      - django
    volumes:
      - ./public/static:/srv/static
      - ./public/media:/srv/media

volumes:
