# Generated by Django 2.1 on 2018-08-20 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buschenschank', '0012_auto_20180819_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCheckResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tag_name', models.CharField(max_length=255)),
                ('website', models.CharField(help_text='URL checked', max_length=255, verbose_name='Website URL')),
                ('return_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('buschenschank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buschenschank.Buschenschank', verbose_name='Buschenschank')),
            ],
            options={
                'verbose_name': 'Page check result',
                'verbose_name_plural': 'Page check results',
                'ordering': ('-created',),
            },
        ),
    ]
