# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buschenschank',
            options={'verbose_name': 'Buschenschank', 'verbose_name_plural': 'Buschenschänken'},
        ),
        migrations.AddField(
            model_name='buschenschank',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buschenschank',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='buschenschank',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
