# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0002_auto_20161028_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='buschenschank',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
