# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import easy_thumbnails.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0004_auto_20161117_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description shown on region page', null=True, verbose_name='Description')),
                ('region_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Image displayed on region page', upload_to='images/regions', verbose_name='Region image')),
                ('areas', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('website', models.URLField(blank=True, null=True)),
                ('calendar_website', models.URLField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True, verbose_name='Notes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
