# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0005_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=8, null=True),
        ),
    ]
