# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 21:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0006_auto_20161120_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=20)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AlterModelOptions(
            name='buschenschank',
            options={'ordering': ('name',), 'verbose_name': 'Buschenschank', 'verbose_name_plural': 'Buschenschänke'},
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together=set([('name', 'district', 'county')]),
        ),
    ]
