# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 16:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0007_auto_20161214_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',), 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelManagers(
            name='buschenschank',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='buschenschank',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='buschenschank',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='buschenschank',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='buschenschank',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=8, null=True, verbose_name='OSM Type'),
        ),
        migrations.AlterField(
            model_name='buschenschank',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='buschenschank',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='county',
            field=models.CharField(max_length=20, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='district',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Multipolygon'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='areas',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Areas'),
        ),
        migrations.AlterField(
            model_name='region',
            name='calendar_website',
            field=models.URLField(blank=True, null=True, verbose_name='Calendar website'),
        ),
        migrations.AlterField(
            model_name='region',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=8, null=True, verbose_name='OSM Type'),
        ),
        migrations.AlterField(
            model_name='region',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='region',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
