# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0009_buschenschank_modified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buschenschank',
            options={'ordering': ('name',), 'verbose_name': 'Buschenschank', 'verbose_name_plural': 'Buschenschanken'},
        ),
    ]
