# Generated by Django 2.0rc1 on 2017-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0010_auto_20171107_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='wikipedia_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
