# Generated by Django 3.1.14 on 2022-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buschenschank', '0012_auto_20180819_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buschenschank',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='Tags'),
        ),
    ]
