server {
    listen [::]:80 default_server;
    listen 80 default_server;

    client_max_body_size 25m;

    root   /srv/;
    try_files $uri @app;

    location @app {
            proxy_pass http://django:8000;
    }
}
